server:
  port: 1002
  
spring:
  zipkin:
    base-url: http://localhost:9411/
  
  application:
    name: USER-SERVICE
    
logging:
  file: E:\IBM-Practice-Micro\microservice.log
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost